# @package _global_

defaults:
  - override /data: libero_2cam
  - override /model: dream_fastwam
  - _self_

output_dir: ./runs/dream_fastwam_libero/${now:%Y-%m-%d}_${now:%H-%M-%S}

batch_size: 16
num_workers: 4
lr_scheduler_type: "cosine"
learning_rate: 1e-4
num_epochs: 2
max_steps: null
log_every: 10
save_every: 2000
eval_every: 0
gradient_accumulation_steps: 1
weight_decay: 1e-2
resume: null
freeze_video_expert: true

data:
  train:
    dream_target:
      enabled: true
      future_offsets: [4]

model:
  mot_checkpoint_mixed_attn: true
  loss:
    lambda_video: 0.0
    lambda_action: 1.0
    lambda_dream: 0.1
  action_noise:
    use_correlated_noise_train: false
    use_correlated_noise_infer: false
